### ISSUE TITLE
Dependency "bna" isn't compatible with python 2.7

### ISSUE THREAD

**Issue by MPX4132** [jleclanche/python-bna#14]
Specifically, it crashes when an attempt is made to xor strings in the function `decrypt(response, opt)`:
```
ret.append(c ^ e) # LINE 90: Bytes aren't supported in python 2.7
```

It'll probably also crash anywhere it uses the `bytes(...)` function.

**Comment by MPX4132** [comment]
I worked around it by using the python 3 equivalent, and making the following changes:
* Installed pip3:
```
apt install python3-pip
```
* Installed the dependency manually:
```
pip3 install bna
```
* Modified the `python-bna/bin/bna`'s interpreter to python3:
```
#!/usr/bin/python3
```
And copied it to the executable path:
```
cp python-bna/bin/bna /usr/local/bin/
```

**Comment by MPX4132** [comment]
Did you guys fix it, or we gonna pretend it’s fixed?

**Comment by jleclanche** [comment]
It's not compatible with python 2.7, and that's intended. You need python 3 to run it.

**Comment by MPX4132** [comment]
What’s the point in making the interpreter ambiguous?

```
#!/usr/bin/env python
```

Why not explicitly say python3? I reported the issue because the script crashed when I tried executing it. Why did it crash? That’s easy, my environment points python to python 2.7, not python 3.x, which is clearly what’s expected here. I think **this is a bug**, not a configuration issue.
