### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by elmstreetvictim** [jleclanche/python-bna#26]
I’m having a hard time. I am using the mobile Authenticator. I fed my provided serial number and the restore code into the bna python binary, and am getting an error that the serial or restore are incorrect. 

I also tried feeding these things into another third party Authenticator and even that is saying that the codes are invalid. I’m curious if blizzard has changed something behind the scenes. 

The official first party app is giving me codes but I want to be able to replicate/clone this just in case

**Comment by jleclanche** [comment]
It still works yes, but I did change the format of the restore code in the config file at some point. However there is a compatibility shim which should work.

You can email me your config file directly if you want and I can see if I can get you your restore code, or check if there's a bug in the app…

**Comment by elmstreetvictim** [comment]
I would like to reference this blizzard forum post that was opened recently.  [Forum Post](https://us.forums.blizzard.com/en/blizzard/t/blizzard-authenticator-bug-an-unexpected-error-occured/12172/16)

 Less than a day ago someone shared this: 

> I contacted their support, and the answer was that “the authenticator […] is phone specific” and “There is no way to just swap the authenticator from phone to phone”.

I was initially under the impression that there was a bug on their backend, seeing that WinAuth, python-bna, the official mobile authenticator on iOS and Android, as well as the same app in an Android emulator WOULD NOT WORK to restore with a working, valid, active authenticator.

I don't mind sending over my information to you via email or something, if you want to try to replicate it. I would love to see what the actual HTTP response is.

**Comment by elmstreetvictim** [comment]
Holy crap it works now. The message board thread I linked got updated with another response by someone who was succesful. I tried again with the native apps and it worked, then tried on python-bna and it works again. Seems like an outage or error on their end that got resolved. Closing this issue

**Comment by jleclanche** [comment]
Great to hear! I've no idea what's behind this then but good you solved it. :)
