### ISSUE TITLE
bna new fails due to KR region

### ISSUE THREAD

**Issue by deadmeu** [jleclanche/python-bna#28]
https://github.com/jleclanche/python-bna/blob/64a4004cc1212fc29224f4d559eec05ddc35a94d/bna/http.py#L92

When creating a new authenticator using `bna new` Blizzard assigns me a serial id in a "KR" region, which breaks this check.
I'm running this in Australia, but a workaround is using a VPN to place yourself in another country such as the US or UK.

It may be necessary for a "KR" region to be added to this list.

**Comment by jleclanche** [comment]
Fixed in 5.0.1, thanks @Davis-A
