### ISSUE TITLE
python-bna usage

### ISSUE THREAD

**Issue by whismerhill** [jleclanche/python-bna#30]
Following a guide from aegis :  https://github.com/beemdevelopment/Aegis/wiki
I'm unable to complete it, neither does reading how to use it from this repo
step 2 : "bna new" gives nothing
I did the pip install successfully
(pip3 list shows bna, click & pyotp)
I tried through regular windows command line & through python itself
I also did a search for "bna" and I only find it in libraries e.g. .\Python38\Lib\site-packages\bna*.py

I guess I'm too much of a newbie maybe ?

Thanks.

**Comment by jleclanche** [comment]
Hey. Neat, I didn't know Aegis recommended bna.

It looks like I messed up packaging of the latest version, it's missing the main script. Let me look into it.

**Comment by jleclanche** [comment]
Try running `pip install --upgrade bna`, it will install bna 5.0.2 and you will be able to run the `bna` command. (If you can't, you can also try `python -m bna` instead of just `bna`)

**Comment by whismerhill** [comment]
worked fine. Thanks.

**Comment by jleclanche** [comment]
Great!
