### ISSUE TITLE
"That authenticator code is invalid." when duplicating mobile app

### ISSUE THREAD

**Issue by catthou** [jleclanche/python-bna#31]
I was really hoping this would be a good way to have a pc-based auth backup, since using my phone does not always suit my physical needs. So I used my mobile app's restore code and serial to "restore" it to bna, but none of the codes from it work. They're not the same as the mobile app nor do they work at all. I just get, "That authenticator code is invalid." But I didn't have any problem or errors setting it up. The restore code and serial look perfect and it spits out codes on command, just none of them work.

```
$ bna --version
bna, version 5.0.2
$ pip --version
pip 21.0.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
$ uname -a
Linux penguin-pc 5.10.27-gentoo #2 SMP PREEMPT Sat May 1 16:52:28 MST 2021 x86_64 AMD Ryzen 9 3900XT 12-Core Processor AuthenticAMD GNU/Linux
```

**Comment by glebmtb** [comment]
+1

**Comment by ChristianBesp** [comment]
Can you confirm if this is still the case? It works for me. I needed to make sure that the restored authenticator in bna is also the default one or given as specific authenticator when using `bna show`. I had a previous authenticator registered and restoring the one from the official mobile app did not register this one as default

**Comment by catthou** [comment]
I have no idea; I haven't touched battle net in eons at this point. I'm not able to be of any more help.

**Comment by jleclanche** [comment]
This should be fixed now, apparently they removed the dashes from the serials...
