### ISSUE TITLE
"Serial number is invalid." when setting up authenticator on Battle.net

### ISSUE THREAD

**Issue by edwardando** [jleclanche/python-bna#32]
I'm putting in my EU-XXXX-YYYY-ZZZZ number and am getting this error on Battle.net, am I doing something wrong?

**Comment by ChristianBesp** [comment]
I had the same issues. After a lot of trial and error, it worked for me when I omitted the dashes. Try `EUXXXXYYYYZZZZ`.

**Comment by ChristianBesp** [comment]
@edwardando If you can confirm, I could provide a pull-request @jleclanche

**Comment by jleclanche** [comment]
Yes please, i can't look into why this is happening right now but I'll review a pull request (if possible with a test attached)

**Comment by ChristianBesp** [comment]
In the official app I still get a serial number that includes dashes. I will investigate a bit, but at least for now omitting them works.

**Comment by edwardando** [comment]
Seems to work perfectly, sorry for this lack of imagination!!
